require "active_support/core_ext/string/strip"
require "octokit"
require 'json'
require 'webrick'

require "ruboty"
require 'ruboty/adapters/github_webhook'
require "ruboty/github/actions/base"
require "ruboty/github/actions/close_issue"
require "ruboty/github/actions/create_branch"
require "ruboty/github/actions/create_issue"
require "ruboty/github/actions/search_issues"
require "ruboty/github/actions/create_pull_request"
require "ruboty/github/actions/merge_pull_request"
require "ruboty/github/actions/remember"
require "ruboty/github/actions/create_release"
require "ruboty/github/actions/get_releases"
require "ruboty/github/actions/get_latest_release"
require "ruboty/github/actions/get_commit_diff"
require "ruboty/github/actions/get_changelog"
require "ruboty/github/version"
require "ruboty/handlers/github"
